name: CI

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    container: nikolodion/esp-idf-qemu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build app
        shell: bash # otherwise github error: "/opt/esp/idf/export.sh: Syntax error: "(" unexpected"
        run: |
          idf.py build

      - name: Build and run tests
        shell: bash
        run: |
          cd ./test
          idf.py qemu_run -DTEST_IN_QEMU=1

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ci-artifacts
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/quadro3.bin
            build/quadro3.elf
            test/build/bootloader/bootloader.bin
            test/build/partition_table/partition-table.bin
            test/build/quadro3_test.bin
            test/build/quadro3_test.elf
            qemu_image.bin
            qemu_log.txt
