name: Docker Image CI

# The CI.yml Action depends on a custom container with qemu and esp-idf installed.
# It is build here based on the Dockerfile under the current folder.

on:
  push:
    paths:
      - '.github/workflows/Dockerfile'
      - '.github/workflows/docker-image.yml'
    branches: master
  pull_request:
    paths:
      - '.github/workflows/Dockerfile'
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: nikolodion
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: .github/workflows/Dockerfile
          push: ${{ github.ref == 'refs/heads/master' && github.event == 'push' }}
          tags: nikolodion/idf-with-qemu:latest

